### PR TITLE
Upgrade JWT library

### PR DESCRIPTION
**Pull request by pascaldekloe**
Good to learn how the library is used. I realised a bit late the audience claim is a listing (by default). Have fun!

### CODE REVIEW

**Comment by pascaldekloe** [comment]
Maybe I can help with the `TODO Find a way around the pascaldekloe/jwt package decoding json numbers as float64 (standard encoding/json Unmarshaling)` if you care to explain the problem?

**Comment by koshatul** [comment]
I'd have to check, but I think it was because the default in json unmarshal is to treat numbers as float64, I think that was an issue with time, I'll try and check it tonight and see what I meant when I put that there.
https://golang.org/pkg/encoding/json/#Decoder.UseNumber

I really should comment clearer :)

Your library is awesome, with my use case having a single audience wasn't a problem.

I'll look tonight and see why the 1.10 test is failing, at a glance it's a change in `rsa.PrivateKey` between 1.10 and 1.11.

**Comment by koshatul** [comment]
It was added to `rsa.PublicKey` in 1.11
https://golang.org/doc/go1.11#crypto/rsa
https://golang.org/pkg/crypto/rsa/#PublicKey.Size

I just saw https://github.com/pascaldekloe/jwt/commit/7d6a3f59a7b8b09a2f84c69bfb7018bc1436e315

I'll accept as-is and add in some tests for tokens with multiple audiences and how that will affect the verifier before I tag the next version, (I think if there's more than one audience, there's a chance it'll return the first audience, but not the matching audience, but maybe it should just return the ).

I'll bump the major for a breaking change on go versions as well.

Thanks for all the work on it.

**Comment by pascaldekloe** [comment]
You are welcome. :-) The test coverage is good here indeed. Maybe jwt.Claims.Raw can help as a fallback with specific unmarshalling requirements.

**Pull request merged**
